export enum ActionTypes {
  SET_POKEMONS = "SET_POKEMONS",
  GET_POKEMONS = "GET_POKEMONS",
  SET_ERROR = "SET_ERROR",
  CLEAR_ERROR = "CLEAR_ERROR",
  TOGGLE_LOADER = "TOGGLE_LOADER",
  ADD_FAVORITE = "ADD_FAVORITE",
  REMOVE_FAVORITE = "REMOVE_FAVORITE",
}
